### PR TITLE
feat: upgrade to Angular 15 and enable partial compilation

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by WoodNeck** [comment]
Hello @arturovt! Thanks for the contribution!

I have a question.
Our modules currently support previous versions of Angular, normally `10.0+` or `11.0+` I guess.
When we apply this patch, can we support backward compatibility for Angular users with lower major versions?
What should be the best practice for this? Please give us some advice, thanks :)

**Comment by arturovt** [comment]
@WoodNeck, I would suggest dropping support for older versions because they're already considered "legacy" and not maintained by the Angular team anymore. See that even Angular 12 is not in LTS: https://angular.io/guide/releases#actively-supported-versions. There was a breaking change in Angular 12 because they released strict support of their APF ([Angular Package Format](https://angular.io/guide/angular-package-format)). It's basically the format and the structure of the package. The format declares NOT to emit UMD bundles, emit only `.mjs` files (ESM compatible), etc.

The partial compilation generates intermediate code compatible between Angular versions (12+), which means it's not tied to a specific compiler version. Note that the current change will allow users to use this package starting from Angular 12 (not 15). P.S. to ensure we can double-check it in any minimal Angular 12 app.

**Comment by WoodNeck** [comment]
@arturovt 
Thanks for the detailed explanation, that really helps!
I'd wish to update all packages right away in that case, but as this is a breaking change, I have to discuss & investigate with our team how the update can affect our users first.
We'll merge this after that. Again, thank you for your contribution!

**Review by WoodNeck — APPROVED** [review]
LGTM

**Review by malangfox — APPROVED** [review]
LGTM

**Pull request merged**
