### PR TITLE
fix: count skip elements

### PR DESCRIPTION
**Pull request by daybrush**
## Issue

#4 

* The skip element should be counted. The reason is that the index is misaligned.
* The skip element occurs preReadyElement and readyElement without any other work.

### CODE REVIEW

**Review by WoodNeck — COMMENTED** [review]
The PR itself looks good to me, but the spec is kinda arguable.
Can you show me some actual examples of #4?

**Comment by daybrush** [comment]
@WoodNeck 
I think it is also controversial. I want to discuss.

```html
<div data-skip="true"></div>
<div></div>
<div></div>
```
```js
import ImReady from "@egjs/imready";
const im = new ImReady().check(document.querySelectorAll("div"));

// readyElement, or error event
im.on("readyElement", e => {
   // Excluding the skip element leads to confusion in the index.
   // 0, 1, 2 (now: 0, 1)
   console.log(e.index);
});
im.on("ready", e => {
   // 3 (now: 2)
   console.log(e.totalCount);
});
```

**Comment by WoodNeck** [comment]
@daybrush 

`totalCount` being 2 looks more natural to me.
When do indexes make such confusion? Were there any cases you experienced while applying it?

**Comment by daybrush** [comment]
@WoodNeck 

When item and element are in 1:1 relationship, this becomes a problem.

If any of the skip elements are included, the meaning of index disappears.


```js
const im = new ImReady().check(items.map(item => item.el));

im.on("readyElement", e => {
    console.log(items[e.index]);
}).on("error", e => {
    console.log(items[e.index]);
});

**Review by WoodNeck — APPROVED** [review]
Okay, I understood :+1: 
Maybe adding property like `isSkip` or sth to the events might make this spec more intuitive I guess.

**Comment by daybrush** [comment]
@WoodNeck 
Oh that's good. I will add it.

**Review by mixed — APPROVED** [review]
🚀🚀🚀🚀🚀

**Pull request merged**
